function [dnamask] = segment_dna_2d(dna)
%segmentImage Segment image using auto-generated code from Image Segmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the Image Segmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 16-Apr-2024
%----------------------------------------------------


% Threshold image with global threshold
gray_dna = imbinarize(im2gray(dna));

% Dilate mask with disk
radius = 2;
decomposition = 0;
se = strel('disk', radius, decomposition);
gray_dna = imdilate(gray_dna, se);

% Create masked image.
dnamask = dna;
dnamask(~gray_dna) = 0;
end

%%
